// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  $("document").ready(function() {
    var app;
    app = {};
    window.app = app;
    app.StatesModel = Backbone.Model.extend({
      initialize: function() {}
    });
    app.StatesCollection = Backbone.Model.extend({
      model: app.StatesModel,
      url: "https://github.com/electionindia/electiondata/blob/master/json/constituency.json",
      parse: function(resp, xhr) {
        return resp.models;
      }
    });
    app.HomeView = Backbone.View.extend({
      el: "#main-view",
      template: "#template-main-view",
      render: function() {
        var h;
        h = _.template($(this.template).html());
        this.$el.html(h);
        return this;
      }
    });
    app.CandidatesView = Backbone.View.extend({
      el: "#main-view",
      template: "#template-candidates",
      render: function() {
        var h;
        h = _.template($(this.template).html());
        this.$el.html(h);
        return this;
      }
    });
    app.Router = Backbone.Router.extend({
      routes: {
        "": "default",
        ":state/:constituency": "viewCandidates"
      },
      initialize: function() {},
      "default": function() {
        var defview;
        defview = new app.HomeView();
        defview.render();
        $(".headersearch").hide();
      },
      viewCandidates: function() {
        var canview;
        canview = new app.CandidatesView();
        canview.render();
        $(".headersearch").show();
      }
    });
    app.router = new app.Router();
    app.StatesCollection = new app.StatesCollection();
    return Backbone.history.start({
      pushState: false,
      root: window.location.pathname
    });
  });

}).call(this);
